[package]
name = "api"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "miccai-backend-rust"
path = "src/main.rs"

[dependencies]
models = { path = "../models" }
services = { path = "../services" }
infrastructure = { path = "../infrastructure" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
actix-web = { workspace = true }
actix-cors = { workspace = true }
tokio = { workspace = true }
env_logger = { workspace = true }
